# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17FjayhLu89STgD2W2MwGkk2bvEQF4vyC

1 : What is Simple Linear Regression (SLR)? Explain its purpose.

Ans:- Simple Linear Regression (SLR) models the relationship between one independent (predictor) variable and one dependent (outcome) variable using a straight line, aiming to understand how changes in the predictor affect the outcome, estimate unknown outcomes, and make predictions. Its purpose is to quantify this linear association (e.g., hours studied vs. test scores), determine its strength, and forecast values, forming a fundamental tool in statistics and machine learning for pattern analysis.
What is SLR?
A statistical and machine learning method that fits a straight line to data points, representing a linear relationship between two continuous variables.
It involves one predictor variable (X) and one outcome variable (Y).
The goal is to find the "line of best fit," often using the Ordinary Least Squares (OLS) method, which minimizes the sum of squared errors (residuals) between the actual data and the line.
Purpose of SLR
Modeling Relationships: To understand the direction (positive/negative) and strength of the linear relationship between two variables (e.g., advertising spend vs. sales).
Prediction: To predict the value of the dependent variable (Y) for a given value of the independent variable (X).
Quantifying Influence: To determine how much the dependent variable changes for each unit change in the independent variable (the slope).
Foundation for More Complex Models: Serves as a building block for more advanced regression techniques (like Multiple Linear Regression).
Example
Predicting a child's weight (Y) based on their age (X). The SLR model finds the best line, allowing you to estimate weight for a specific age, showing how weight tends to increase with age.

2: What are the key assumptions of Simple Linear Regression?

ans:- Simple Linear Regression (SLR) relies on key assumptions for valid results: a Linear Relationship between variables, Homoscedasticity (constant error variance), Independence of Errors, and Normality of Residuals, plus the absence of Multicollinearity (though less critical in SLR with only one predictor) and a zero conditional mean for errors, ensuring the line accurately models the data's central tendency and error spread.
Here are the core assumptions explained:
Linearity: The relationship between the independent (X) and dependent (Y) variables must be a straight line. Changes in X should lead to proportional changes in Y.
Independence of Errors (No Autocorrelation): Errors (residuals) from one observation should not predict errors from another; they must be uncorrelated.
Homoscedasticity (Constant Variance): The variance of the errors should be the same across all levels of the independent variable. Residuals should scatter evenly.
Normality of Errors: The errors (residuals) should be normally distributed, which is crucial for hypothesis testing and confidence intervals.
Zero Conditional Mean of Errors: The average error for any given value of the independent variable should be zero, meaning the model captures the central trend, not systematic bias.
No Multicollinearity: In SLR, this is inherently met as there's only one predictor, but in multiple regression, it means independent variables shouldn't be highly correlated with each other.
Violating these assumptions can lead to inaccurate predictions, unreliable coefficients, and invalid statistical inferences, requiring data transformation or different modeling approaches.

3: Write the mathematical equation for a simple linear regression model and
explain each term.

ans:- A simple linear regression model describes the linear relationship between a single independent variable and a dependent variable. The mathematical equation is: \(y=\beta _{0}+\beta _{1}x+\epsilon \)Each term in the equation is explained below: \(y\):This is the dependent variable (or response variable) that you are trying to predict or explain.\(x\):This is the independent variable (or predictor variable), which is the factor used to predict the value of \(y\).\(\beta _{0}\) (beta naught):This is the y-intercept. It represents the expected mean value of \(y\) when \(x\) is equal to 0.\(\beta _{1}\) (beta one):This is the slope (or regression coefficient) of the line. It represents the change in \(y\) for a one-unit change in \(x\).\(\epsilon \) (epsilon):This is the error term (or residual). It represents the difference between the actual observed value of \(y\) and the value of \(y\) predicted by the linear model, capturing all other factors not accounted for by \(x\). In practical applications, when the model is estimated from data, the estimated equation is often written as: \(\^{y}=\^{\beta }_{0}+\^{\beta }_{1}x\)Here, \(\^{y}\) (y-hat) is the predicted value of the dependent variable, and \(\^{\beta }_{0}\) and \(\^{\beta }_{1}\) are the estimated coefficients for the intercept and slope, respectively

4: Provide a real-world example where simple linear regression can be
applied.

ans:- A great real-world example for simple linear regression is predicting a student's exam score based on the number of hours they studied, where study hours (independent variable) linearly influence the final score (dependent variable), helping educators understand the impact of study time and potentially forecast performance. How it Works Data Collection: Gather data from students, noting how many hours each student studied for a test and their corresponding exam score.Identify Variables:Independent Variable (X): Hours Studied (the predictor)Dependent Variable (Y): Exam Score (the outcome)Model Fitting: Simple linear regression finds the best-fit straight line (equation: \(Y=\beta _{0}+\beta _{1}X\)) that describes this relationship, showing how much the score changes for each additional hour of study.Prediction: Once the line is established, you can use it to predict a student's likely score if you know their study time, or assess the strength of that relationship. Other Examples Sales Forecasting: Predicting monthly sales based on advertising spend.Healthcare: Relating drug dosage to treatment effectiveness.Real Estate: Estimating house prices based on square footage.

5: What is the method of least squares in linear regression?

ans:- The method of least squares in linear regression finds the "best fit" line for a set of data points by minimizing the sum of the squared vertical distances (errors or residuals) between the actual data points and the line itself. It calculates the slope and intercept of this line (like \(y=mx+b\)) to represent the underlying trend, allowing for predictions, by making these squared errors as small as possible, avoiding issues with positive and negative errors canceling out. How it works (the core idea): Plot Data: You have a scatter plot of (x, y) data points.Propose a Line: Imagine drawing many different straight lines through the data.Calculate Errors (Residuals): For each data point, find the vertical distance (error) between the point and the line.Square the Errors: Square each of these distances to make them all positive and penalize larger errors more heavily.Sum the Squares: Add up all the squared errors.Find the Minimum: The least squares method identifies the specific line where this total sum of squared errors is the smallest possible value. Key Formulas (for simple linear regression \(y=mx+b\)): Slope (\(m\)): \(m=\frac{n(\sum xy)-(\sum x)(\sum y)}{n(\sum x^{2})-(\sum x)^{2}}\).Y-intercept (\(b\)): \(b=\={y}-m\={x}\) (where \(\={x}\) and \(\={y}\) are the means of x and y). Why it's used: Data Modeling: To understand the relationship between variables (e.g., sales vs. temperature).Prediction: To forecast future outcomes based on the identified trend.Foundation: It's a fundamental technique in statistics, data science, economics, and many other fields.

6: What is Logistic Regression? How does it differ from Linear Regression?

ans- Logistic Regression predicts categorical outcomes (like Yes/No, Spam/Not Spam) using probabilities (0-1) via the S-shaped sigmoid function, ideal for classification; while Linear Regression predicts continuous values (like price, temperature) by fitting a straight line to data, perfect for regression tasks, making the core difference the type of output: categorical for Logistic vs. continuous for Linear.
Logistic Regression
Purpose: Classification problems (e.g., disease diagnosis, spam detection).
Output: A probability (0 to 1) of belonging to a specific category (e.g., 80% chance of spam).
Function: Uses the Sigmoid (logistic) function to map linear outputs to probabilities, resulting in an S-shaped curve.
Underlying Math: Models the log-odds of an event.
Linear Regression
Purpose: Regression problems (e.g., predicting house prices, sales).
Output: A continuous numerical value (e.g., $250,000, 75°F).
Function: Fits a straight line (or plane) to the data points.
Underlying Math: Models a direct linear relationship between variables.
Key Differences Summarized
Problem Type: Logistic (Classification) vs. Linear (Regression).
Dependent Variable: Logistic (Categorical) vs. Linear (Continuous).
Output: Logistic (Probability, 0-1) vs. Linear (Any number).
Curve: Logistic (S-shaped) vs. Linear (Straight Line).
Estimation Method: Logistic (Maximum Likelihood) vs. Linear (Least Squares).

7: Name and briefly describe three common evaluation metrics for regression
models.

ans- Three common evaluation metrics for regression models are Mean Absolute Error (MAE), Mean Squared Error (MSE), and the R-squared (R²) score.
1. Mean Absolute Error (MAE)
MAE measures the average magnitude of the errors between the predicted and actual values. It is calculated as the mean of the absolute differences.
Description: MAE provides a direct, easily interpretable measure of average error in the same units as the target variable. Because it uses absolute values, all errors are weighted equally, making it robust to outliers.
2. Mean Squared Error (MSE)
MSE measures the average of the squared differences between the predicted and actual values.
Description: By squaring the errors, this metric penalizes larger errors more heavily than smaller ones, making it sensitive to outliers. The resulting value is in the squared unit of the output variable, which can make it harder to interpret than MAE.
3. R-squared (R²) Score (Coefficient of Determination)
R-squared is a statistical measure that represents the proportion of the variance in the dependent variable that is predictable from the independent variables.
Description: It provides an indication of the "goodness of fit" of the model, ranging from 0 to 1. An R² of 1 indicates that the model perfectly fits the data, explaining all the variability, while a value near 0 suggests the model explains very little of the variance compared to a simple mean-based model.

8: What is the purpose of the R-squared metric in regression analysis?

ans- The purpose of the R-squared (\(\text{R}^{2}\)) metric, also known as the coefficient of determination, in regression analysis is to represent the proportion of the variance in the dependent variable that is predictable from the independent variable(s) [1, 2]. Key aspects of its purpose and interpretation include: Explained Variance: It provides a measure of how well the regression model fits the observed data [3, 4]. A higher R-squared value indicates that a larger percentage of the variations in the target variable can be explained by the model's inputs [3].Goodness of Fit: R-squared is essentially a statistical measure of how close the data are to the fitted regression line [2, 5].Range: The value of R-squared typically ranges from 0 to 1 (or 0% to 100%).An R-squared of 0 indicates that the model explains none of the variability of the response data around its mean [3].An R-squared of 1 (or 100%) indicates that the model explains all the variability in the response data around its mean [3].Model Comparison (with caution): While a higher R-squared generally suggests a better fit, it's not the sole determinant of model quality. It does not indicate whether a regression model is adequate, nor does it quantify if the coefficient estimates and predictions are biased [2, 5]. In summary, R-squared helps analysts and researchers understand the strength of the relationship between their model's predictions and the actual observed values [3].

9: Write Python code to fit a simple linear regression model using scikit-learn
and print the slope and intercept.
(Include your Python code and output in the code box below.)

ans-
"""

import numpy as np
from sklearn.linear_model import LinearRegression

# 1. Create sample data (features X and target y)
# In a real scenario, you would load your data from a file or database.
X = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)  # Features must be a 2D array
y = np.array([2, 3, 5, 4, 6])              # Target variable

# 2. Create a linear regression model instance
model = LinearRegression()

# 3. Fit the model to the data
# The model learns the best slope and intercept from the provided data.
model.fit(X, y)

# 4. Print the learned slope (coefficient) and intercept
# .coef_[0] is used because the model treats single-feature input as an array of coefficients
# even though we only have one feature.
print(f"Slope (Coefficient): {model.coef_[0]:.4f}")
print(f"Intercept: {model.intercept_:.4f}")

# 5. Optional: Make a prediction (for demonstration)
# For example, predict the value for a new feature value of 6
new_data = np.array([[6]])
prediction = model.predict(new_data)
print(f"\nPrediction for X=6: {prediction[0]:.4f}")

# Expected Output (will be similar based on the simple data):
# Slope (Coefficient): 0.9000
# Intercept: 1.1000
#
# Prediction for X=6: 6.5000

"""10: How do you interpret the coefficients in a simple linear regression model?

ans- In a simple linear regression (\(Y=B_{0}+B_{1}X+e\)), the slope coefficient (\(B_{1}\)) tells you the average change in the dependent variable (\(Y\)) for a one-unit increase in the independent variable (\(X\)); a positive \(B_{1}\) means \(Y\) increases with \(X\), while a negative \(B_{1}\) means \(Y\) decreases. The intercept (\(B_{0}\)) is the predicted value of \(Y\) when \(X\) is zero, but it's only meaningful if \(X=0\) is a plausible value in your data. Interpreting the Slope (\(B_{1}\)) Direction: The sign (+ or -) indicates the relationship's direction.Positive Coefficient: As \(X\) goes up, the average \(Y\) also goes up.Negative Coefficient: As \(X\) goes up, the average \(Y\) goes down.Magnitude: The number itself shows the amount of change.Example: If \(B_{1}=0.79\) for R&D spend (X) on profit (Y), then for every $1 increase in R&D, profit increases by $0.79 (79 cents) on average.Example: If \(B_{1}=-255\) for car age (X, in years) on selling price (Y), then for each year older a car gets, the price drops by $255, all else equal. Interpreting the Intercept (\(B_{0}\)) This is the predicted \(Y\) value when \(X=0\).Context is Key: If \(X=0\) is not in your data range or doesn't make sense (e.g., a house with zero square footage), the intercept has no practical meaning and just helps position the regression line. Key Things to Remember Units: Always relate the coefficient back to the units of your variables (e.g., dollars, years, cm)."All Else Equal": The interpretation assumes you're holding other factors constant (though in simple regression, there are no other predictors).Correlation vs. Causation: Regression shows association, not necessarily cause and effect.
"""